### ISSUE TITLE
Could not compile after migration to v2

### ISSUE THREAD

**Issue by gigikj** [jaredh159/tailwind-react-native-classnames#100]
BUNDLE  ./index.js 

error: Error: Unable to resolve module fs from /Users/XXXXX/Documents/rect-native/cinntab/node_modules/tailwindcss/lib/plugins/preflight.js: fs could not be found within the project or in these directories:
  node_modules/tailwindcss/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
   6 | exports.default = _default;
   7 |
>  8 | var _fs = _interopRequireDefault(require("fs"));
     |                                           ^
   9 |
  10 | var _postcss = _interopRequireDefault(require("postcss"));
  11 |
    at ModuleResolver.resolveDependency (/Users/gigijoseph/Documents/rect-native/cinntab/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (/Users/gigijoseph/Documents/rect-native/cinntab/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/gigijoseph/Documents/rect-native/cinntab/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/gigijoseph/Documents/rect-native/cinntab/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/gigijoseph/Documents/rect-native/cinntab/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/gigijoseph/Documents/rect-native/cinntab/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/gigijoseph/Documents/rect-native/cinntab/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by jaredh159** [comment]
can you give me some more information and context? is your project open source? how about pasting your package.json.
