### ISSUE TITLE
Unable to run the app with next rc (2.0.0-rc.4)

### ISSUE THREAD

**Issue by afkcodes** [jaredh159/tailwind-react-native-classnames#62]
This is the log that keeps popping up
`
If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
> 1 | import resolveConfig from 'tailwindcss/resolveConfig';
    |                            ^
  2 | import Cache from './cache';
  3 | import ClassParser from './ClassParser';
  4 | import { parseInputs } from './parse-inputs';
    at ModuleResolver.resolveDependency (/Users/ashish/radio/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (/Users/ashish/radio/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/ashish/radio/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/ashish/radio/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/ashish/radio/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/ashish/radio/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/ashish/radio/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async addDependency (/Users/ashish/radio/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
`

**Comment by jaredh159** [comment]
`tailwindcss` is a peer dep. do you have it installed?  `npm i tailwindcss` and try again, if not.

**Comment by afkcodes** [comment]
gotcha, will do that. I did not had tailwind installed. thanks
