### ISSUE TITLE
Jest failing

### ISSUE THREAD

**Issue by franco-marini** [jaredh159/tailwind-react-native-classnames#77]
Hey guys, I'm trying to create some tests for the component while using this library for the styles but I'm getting this issue:
```
Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

By default "node_modules" folder is ignored by transformers.

Here's what you can do:
 • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
 • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/configuration
For information about custom transformations, see:
https://jestjs.io/docs/code-transformation

Details:

<project_path>/node_modules/twrnc/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import resolveConfig from 'tailwindcss/resolveConfig';
                                                                                      ^^^^^^

SyntaxError: Cannot use import statement outside a module

      1 | import { create } from 'twrnc'
      2 |
    > 3 | const tw = create(require(`../../tailwind.config.js`))
        |          ^
      4 |
      5 | export default tw
      6 |

      at Runtime.createScriptFromCode (../../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/styles/index.ts:3:10)
```

**Comment by jaredh159** [comment]
I've struggled with this same thing a bunch of times, it's always a hassle getting RN to play nice with Jest.

But, for instance, I have it working in this project.  I would look at the `babel.config.js` and `jest.config.json` and the package deps. My hunch is if you do 3 things, it will probably work:

First, make your `jest.config.json` look like this:

```json
{
  "preset": "react-native",
  "transform": {
    "^.+\\.tsx?$": "ts-jest"
  },
  "testRegex": "__tests__/.*spec\\.ts$"
}
```

Second, add a `babel.config.js` something like so:

```js
module.exports = {
  presets: [`module:metro-react-native-babel-preset`],
};
```

And then, third, make sure you `npm install -D metro-react-native-babel-preset`.  I _think_ those are the things that got it working for this project, but I remember struggling a bit (and also in other projects), so I can't say 100%.  Please let me know if that works for you.

**Comment by franco-marini** [comment]
Hey @jaredh159, after trying your approach, I couldn’t get it to work as expected. But I found a solution by adding this on the `jest.config.json`
```
transformIgnorePatterns: [
  '/node_modules/(?!@react-native|react-native|twrnc)',
],
```
This solution ignores the transform of the `twrnc` package. But right now, I’m getting the `tailwind.config.js` file in the coverage.
```
-------------------------------------------------|---------|----------|---------|---------|-------------------
File                                             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------------------------------------|---------|----------|---------|---------|-------------------
All files                                        |   53.76 |    30.18 |   56.25 |   93.33 |                   
 react-native                                    |   27.27 |        0 |   33.33 |      75 |                   
  tailwind.config.js                             |   27.27 |        0 |   33.33 |      75 | 1                 
 react-native/src/components/ui/inputs/textfield |   57.57 |    38.88 |      75 |     100 |                   
  styles.ts                                      |   66.66 |       50 |      75 |     100 | 1                 
  textfield.tsx                                  |    54.9 |    33.33 |      75 |     100 | 1                 
 react-native/src/components/ui/text             |    56.7 |    33.33 |   53.33 |   93.33 |                   
  index.ts                                       |   30.76 |        0 |       0 |     100 | 1                 
  styles.ts                                      |   72.22 |     37.5 |   66.66 |     100 | 1                 
  text.tsx                                       |   65.51 |       50 |      75 |     100 | 1                 
  types.ts                                       |       0 |        0 |       0 |       0 | 1                 
 react-native/src/styles                         |   33.33 |        0 |       0 |     100 |                   
  index.ts                                       |   33.33 |        0 |       0 |     100 | 1                 
-------------------------------------------------|---------|----------|---------|---------|-------------------
```
To give a little more context regarding this, I’m using the tailwind custom config and a framework called Nx

PD: This is my `jest.config.json`
```
module.exports = {
  displayName: 'mobile-storybook',
  preset: 'react-native',
  testRunner: 'jest-jasmine2',
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html', 'tsx', 'jsx'],
  setupFilesAfterEnv: ['<rootDir>/test-setup.ts'],
  moduleNameMapper: {
    '.svg': '@nrwl/react-native/plugins/jest/svg-mock',
  },
  transform: {
    '\\.(js|ts|tsx)$': require.resolve('react-native/jest/preprocessor.js'),
    '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$': require.resolve(
      'react-native/jest/assetFileTransformer.js'
    ),
  },
}
```

**Comment by jaredh159** [comment]
Thanks for reporting back -- the `transformIgnorePatterns` rings a bell, I feel like I've used that approach in some other projects to get jest to play nicely with RN and related packages.

I'm a big jest user, but have never done anything with code coverage, so I can't really speak to that.  But I'm guessing there's some way to indicate that you want to ignore the `tailwind.config.js` file for the sake of code coverage reports.
